# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# automatically set facts based on interfaces present
---
- name: setting eth0 to zookeeper interface
  set_fact:
    zookeeper_interface: "{{ hostvars[inventory_hostname].ansible_eth0.device }}"
    zookeeper_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}"
    zookeeper_broadcast_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.broadcast }}"
    zookeeper_metrics_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}"
  when: hostvars[inventory_hostname].ansible_eth0 is defined

# zookeeper is always eth0; this is left here in case we move it to the data plane
# - name: setting eth1 to metrics
#   set_fact:
#     zookeeper_interface: "{{ hostvars[inventory_hostname].ansible_eth1.device }}"
#     zookeeper_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
#     zookeeper_broadcast_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.broadcast }}"
#     zookeeper_metrics_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
#   when: hostvars[inventory_hostname].ansible_eth1 is defined
