cruisecontrol:
  version: '2.0.36'
  frontend: yes
  frontend_version: '0.2.0'
  source_dir: '/usr/local/src'
  config_file: /usr/local/src/cruise-control/config/cruisecontrol.properties
  ui_config_file: /usr/local/src/cruise-control/cruise-control-ui/dist/static/config.csv
  service_name: cruise-control
  user_service: /usr/local/bin
  # environment:
  config:
    port: '9090'
    log: /var/log/linkedin/cruise-control
  packages:
    gradle_version: '5.2.1'
  