# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during confluent platform installation
---
- name: restart sshd
  systemd:
    name: sshd
    state: restarted
  
- name: reload systemd
  command: systemctl daemon-reload
