# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')
  
- name: systemd ksql
  listen: "restart ksql"
  systemd:
    name: "{{ ksql.service_name }}"
    state: restarted
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')

- name: sysvinit ksql
  listen: "restart ksql"
  sysvinit:
    name: "{{ ksql.service_name }}"
    state: restarted
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '<')

- name: user ksql
  listen: "restart ksql"
  command: "{{ ksql.user_service }}/confluent-ksql restart"
  when:
    - not got_root
    