# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# routines for provisioning registry services
---
# this isn't strictly necessary for the registry, but the zookeeper default variables need JVM settings
- import_tasks: tune.yml

- import_tasks: interface-facts.yml

- block:
  
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | configuring {{ schema.registry.service_name }} listeners 
    lineinfile:
      path: "{{ schema.registry.config_file }}"
      regexp: '^listeners='
      line: "listeners=http://{{ registry_interface_ipv4 }}:{{ schema.registry.config.schema_registry_listener_port }}"
    notify: restart registry

  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | configuring {{ schema.registry.service_name }} zookeeper
    lineinfile:
      path: "{{ schema.registry.config_file }}"
      regexp: '^kafkastore.connection.url='
      line: "kafkastore.connection.url={{ groups['zookeeper'] | join(':' + zookeeper.config.port + ',') }}:{{ zookeeper.config.port }}"
    notify: restart registry

  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | ensuring {{ schema.registry.user_service }} exists
    file:
      path: "{{ schema.registry.user_service }}"
      owner: root
      group: root
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | ensuring {{ schema.registry.config.log_dir }} exists
    file:
      path: "{{ schema.registry.config.log_dir }}"
      owner: "{{ schema.registry.user }}"
      group: "{{ schema.registry.group }}"
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | installing {{ schema.registry.service_name }} into {{ schema.registry.user_service }}
    template:
      src: confluent.registry.j2
      dest: "{{ schema.registry.user_service }}/confluent-schema-registry"
      mode: 0755
      owner: "{{ schema.registry.user }}"
      group: "{{ schema.registry.group }}"
      
  become: yes
  
- block:
  
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | creating systemd override directory
    file:
      path: "{{ schema.registry.systemd_override }}"
      owner: "{{ schema.registry.user }}"
      group: "{{ schema.registry.group }}"
      state: directory
      mode: 0750
  
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | installing {{ schema.registry.service_name }} environment overrride
    template:
      src: environment.j2
      dest: "{{ schema.registry.systemd_override }}/override.conf"
      mode: 0640
      owner: "{{ schema.registry.user }}"
      group: "{{ schema.registry.group }}"
    notify:
      - reload systemd
      - restart registry
    when: 
      - ansible_distribution_version is version_compare('7', '>=')
      
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | enabling {{ schema.registry.service_name }} by systemd
    systemd:
      name: "{{ schema.registry.service_name }}"
      enabled: yes
    when: 
      - ansible_distribution_version is version_compare('7', '>=')
  
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | installing sysvinit {{ schema.registry.service_name }} script
    template:
      src: confluent.sysvinit.j2
      dest: "/etc/init.d/{{ schema.registry.service_name }}"
      mode: 0755
      owner: root
      group: root
    when: 
      - ansible_distribution_version is version_compare('7', '<')
      
  - name: CONFLUENT OVERLAY (SCHEMA REGISTRY) | enabling {{ schema.registry.service_name }} by sysvinit
    sysvinit:
      name: "{{ schema.registry.service_name }}"
      enabled: yes
    when: 
      - ansible_distribution_version is version_compare('7', '<')
      
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  