# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
---
confluent:
  packages:
    epel_version: '7-11'
    java_version: '1.8.0'
    confluent_version: '5.3'
    minor_release: '0'
    scala_version: '2.12'
    # confluent_version: '5.2'
    # minor_release: '1'
    # scala_version: '2.12'
    # kafka_version isn't used under confluent, here mainly to match apache
    kafka_version: '2.1'
confluent_os_releasever: '7'
confluent_public_key: "https://packages.confluent.io/rpm/{{ confluent.packages.confluent_version }}/archive.key"
# setting this to no installs the enterprise platform
confluent_community: no
