# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')
    
- name: systemd broker
  listen: "restart broker"
  systemd:
    name: "{{ broker_service_name }}"
    state: restarted
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')

- name: sysvinit broker
  listen: "restart broker"
  sysvinit:
    name: "{{ broker_service_name }}"
    state: restarted
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '<')

- name: user broker
  listen: "restart broker"
  command: "{{ kafka.user_service }}/broker restart"
  when:
    - not got_root
    
- name: pause
  listen: "restart broker"
  pause:
    seconds: 30     
