# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: true
  
- name: restart broker
  listen: "restart broker"
  systemd:
    name: "{{ broker_service_name }}"
    state: restarted
  become: true

- name: pause
  listen: "restart broker"
  pause:
    seconds: 30     
