# configuration variables for zookeeper services
zookeeper:
  apache:
    user: kafka
    group: kafka
    service_name: apache-zookeeper
    systemd_override: /etc/systemd/system/apache-zookeeper.service.d
    config_file: "{{ apache.install_dir }}/kafka_{{ packages.scala_version }}-{{ packages.kafka_version }}/config/zookeeper.properties"
  confluent:
    user: cp-kafka
    group: confluent
    service_name: confluent-zookeeper
    systemd_override: /etc/systemd/system/confluent-zookeeper.service.d
    config_file: /etc/kafka/zookeeper.properties
  user_service: /usr/local/bin
  config:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    tickTime: 2000
    autopurge_snapRetainCount: 10
    autopurge_purgeInterval: 1
    dataDir: /var/lib/zookeeper
    # this needs to be quoted as a string for concatenation purposes
    # if this gets changed it all needs to be changed under kafka defaults
    port: '2181'
  environment:
    KAFKA_HEAP_OPTS: "-Xmx{{ jvm_heap_mem }}g -Xms{{ jvm_heap_mem }}g"
    LOG_DIR: /var/log/kafka
