# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# configuration variables for zookeeper services
zookeeper:
  apache:
    user: kafka
    group: kafka
    service_name: apache-zookeeper
    systemd_override: /etc/systemd/system/apache-zookeeper.service.d
    config_file: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/config/zookeeper.properties"
  confluent:
    user: "{{ (got_root | default('yes')) | ternary('cp-kafka', ansible_user) }}"
    group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    service_name: confluent-zookeeper
    systemd_override: /etc/systemd/system/confluent-zookeeper.service.d
    config_file: "{{ (got_root | default('yes')) | ternary('/etc/kafka/zookeeper.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/kafka/zookeeper.properties')) }}"
  user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
  config:
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    tickTime: 2000
    autopurge_snapRetainCount: 10
    autopurge_purgeInterval: 1
    dataDir: "{{ zookeeper_data_dir | default('/var/lib/zookeeper') }}"
    # this needs to be quoted as a string for concatenation purposes
    port: '2181'
    peers: '2888'
    leaders: '3888'
  environment:
    KAFKA_HEAP_OPTS: "-Xmx{{ jvm_heap_mem }}g -Xms{{ jvm_heap_mem }}g"
    LOG_DIR: "{{ (got_root | default('yes')) | ternary('/var/log/kafka', confluent_root + '/var/log/kafka')}}"
