# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# handlers used during confluent replicator installation
---
- name: user replicator
  listen: "stop replicator"
  command: /usr/local/bin/kafka-connect-replicator stop
  become: yes
  when:
    - got_root | default('yes')

- name: user replicator
  listen: "start replicator"
  command: /usr/local/bin/kafka-connect-replicator start
  become: yes
  when:
    - got_root | default('yes')
    
- name: user replicator
  listen: "restart replicator"
  command: "{{ replicator.user_service }}/kafka-connect-replicator restart"
  when:
    - not got_root
