# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')
    
- name: systemd registry
  listen: "restart registry"
  systemd:
    name: "{{ schema.registry.service_name }}"
    state: restarted
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')

- name: sysvinit registry
  listen: "restart registry"
  sysvinit:
    name: "{{ schema.registry.service_name }}"
    state: restarted
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '<')

- name: user registry
  listen: "restart registry"
  command: "{{ schema.registry.user_service }}/confluent-schema-registry restart"
  when:
    - not got_root
    