# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# install kafka cluster helper utilities
---
- getent:
    database: passwd
    key: "{{ zookeeper.apache.user }}"
    fail_key: False

- set_fact:
    zookeeper_user: "{{ (getent_passwd[zookeeper.apache.user] is none) | ternary(zookeeper.confluent.user, zookeeper.apache.user) }}"
    
- getent:
    database: passwd
    key: "{{ kafka.apache.user }}"
    fail_key: False
  
- set_fact:
    broker_user: "{{ (getent_passwd[kafka.apache.user] is none) | ternary(kafka.confluent.user, kafka.apache.user) }}"

- set_fact:
    broker_service_name: "{{ (getent_passwd[kafka.apache.user] is none) | ternary(kafka.confluent.service_name, kafka.apache.service_name) }}"

- set_fact:
    broker_config_file: "{{ (getent_passwd[kafka.apache.user] is none) | ternary(kafka.confluent.config_file, kafka.apache.config_file) }}"
    
- getent:
    database: group
    key: "{{ kafka.apache.group }}"
    fail_key: False
    
- set_fact:     
     broker_group: "{{ (getent_passwd[kafka.apache.group] is none) | ternary(kafka.confluent.group, kafka.apache.group) }}"

# - debug: msg="{{ zookeeper_user }} {{ broker_user }} {{ broker_group }} {{ broker_service_name }} {{ broker_config_file }}"
#
# - pause:
  
- set_fact:
    apache_bin: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/bin"

- set_fact:
    dn_bin_path: "{{ (got_root | default('yes')) | ternary('/usr/bin', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/bin')) }}"
    
- set_fact: 
    utils_path: "{{ (getent_passwd[kafka.apache.user] is none) | ternary(dn_bin_path, apache_bin) }}"

- set_fact: 
    bin_suffix: "{{ (getent_passwd[kafka.apache.user] is none) | ternary('', '.sh') }}"
    
- block:

  - name: KAFKA OVERLAY (POSTFLIGHT) | installing kafka topic list utility to {{ postflight.utilsDir }}
    template:
      src: list-topics.j2
      dest: "{{ postflight.utilsDir }}/list-topics"
      mode: 0755
      owner: "{{ broker_user }}"
      group: "{{ broker_group }}"
    when:
      - groups['zookeeper'] is defined
      - groups['zookeeper'] | length > 0
      
  - name: KAFKA OVERLAY (POSTFLIGHT) | installing kafka topic describe utility to {{ postflight.utilsDir }}
    template:
      src: describe-topic.j2
      dest: "{{ postflight.utilsDir }}/describe-topic"
      mode: 0755
      owner: "{{ broker_user }}"
      group: "{{ broker_group }}"
    when:
      - groups['zookeeper'] is defined
      - groups['zookeeper'] | length > 0
      
  - name: KAFKA OVERLAY (POSTFLIGHT) | installing kafka topic consume utility to {{ postflight.utilsDir }}
    template:
      src: consume-topic.j2
      dest: "{{ postflight.utilsDir }}/consume-topic"
      mode: 0755
      owner: "{{ broker_user }}"
      group: "{{ broker_group }}"
    when:
      - groups['kafka_broker'] is defined
      - groups['kafka_broker'] | length > 0
      
  become: "{{ got_root | default('yes') }}"