# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# apply AWS kafka rest proxy security group rules for multi-interface systems
---
- name: CONFLUENT OVERLAY | discovering kafka rest proxy instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}" 
      "tag:Application": 'rest_proxy'
      "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: all_rest_nodes
  when: cloud == 'aws'

- block:
  
  - set_fact:
      rest_interfaces: "{{ all_rest_nodes.instances | map(attribute='network_interfaces') | list }}"

  # apply confluent rule and the internal SSH rule 
  - name: CONFLUENT OVERLAY | applying kafka rest proxy internal security rules to interface 0
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_ssh_private.security_groups.0.group_id }}"
    with_items: "{{ rest_interfaces }}"
    when: item.attachment.device_index == 0
  
  # apply confluent external rest proxy rules 
  - name: CONFLUENT OVERLAY | applying kafka rest proxy external security rules to interface 1
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_restproxy_external.group_id }}"
    with_items: "{{ rest_interfaces }}"
    when: item.attachment.device_index == 1
  
  when: "'rest_proxy' in groups | default([])"
