# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# apply AWS kafka connect security group rules for multi-interface systems
---
- name: CONFLUENT OVERLAY | discovering kafka connect instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}" 
      "tag:Application": 'kafka_connect'
      "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: all_connect_nodes
  when: cloud == 'aws'

- block:
  
  - set_fact:
      connect_interfaces: "{{ all_connect_nodes.instances | map(attribute='network_interfaces') | list }}"

  - name: CONFLUENT OVERLAY | applying kafka connector internal security rules to interface 0
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        # - "{{ sg_kafka_connect_internal.group_id }}"
        - "{{ sg_ssh_private.security_groups.0.group_id }}"
    with_items: "{{ connect_interfaces }}"
    when: item.attachment.device_index == 0
  
  # apply confluent external connect rules 
  - name: CONFLUENT OVERLAY | applying kafka connect external security rules to interface 1
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_kafka_connect_external.group_id }}"        
    with_items: "{{ connect_interfaces }}"
    when: item.attachment.device_index == 1
  
  when: "'kafka_connect' in groups | default([])"
