# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# apply AWS cruise control security group rules for multi-interface systems
---
- name: CRUISE CONTROL OVERLAY | discovering cruise control instances
  ec2_instance_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Tenant": "{{ tenant }}"
      "tag:Project": "{{ project }}"
      "tag:Domain": "{{ domain }}"
      "tag:Application": 'cruisecontrol'
      "tag:Cluster": "{{ cluster | default ('a') }}"
      "tag:Dataflow": "{{ dataflow | default ('none') }}"
  register: all_cruisecontrol_nodes
  when:
    - cloud == 'aws'
    - "'cruisecontrol' in groups | default([])"

- block:

  # construct list of all interfaces attached to cruise control nodes
  - set_fact:
      cruisecontrol_interfaces: "{{ all_cruisecontrol_nodes.instances | map(attribute='network_interfaces') | list }}"

  # apply internal SSH rule
  - name: CRUISE CONTROL OVERLAY | applying ssh security rules to interface 0
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_ssh_private.security_groups.0.group_id }}"
    with_items: "{{ cruisecontrol_interfaces }}"
    when: item.attachment.device_index == 0
    
  # apply cruise control rule and the internal SSH rule
  - name: CRUISE CONTROL OVERLAY | applying cruise control security rules to interface 1
    ec2_eni:
      region: "{{ region }}"
      eni_id: "{{ item.network_interface_id }}"
      security_groups:
        - "{{ sg_cruisecontrol_external.group_id }}"
    with_items: "{{ cruisecontrol_interfaces }}"
    when: item.attachment.device_index == 1

  when:
    - "'cruisecontrol' in groups | default([])"
    - groups.cruisecontrol | length > 0
