# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# create AWS kafka ksql security group rules
---
- name: CONFLUENT OVERLAY | creating confluent kafka ksql private external security group
  local_action:
    module: ec2_group
    name: "dnsg_{{ project }}_ksql_private_external"
    description: "kafka ksql external ingress and unrestricted egress rules (ansible)"
    vpc_id: "{{ specified_vpc.vpcs.0.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: "{{ ksql.config.listener_port }}"
        to_port: "{{ ksql.config.listener_port }}"
        cidr_ip: "{{ external_subnet }}"
    rules_egress:
      # Allow all outbound
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: "'kafka_ksql' in groups | default([])"
  register: sg_ksql_external
