# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# create AWS zookeeper security group rules
---
- name: CONFLUENT OVERLAY | creating confluent zookeeper security group
  local_action:
    module: ec2_group
    name: "dnsg_{{ project }}_zookeeper_private_internal"
    description: "zookeeper ingress and unrestricted egress rules (ansible)"
    vpc_id: "{{ specified_vpc.vpcs.0.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: "{{ zookeeper.config.port }}"
        to_port: "{{ zookeeper.config.port }}"
        cidr_ip: "{{ internal_subnet }}"
      - proto: tcp
        from_port: "{{ zookeeper.config.peers }}"
        to_port: "{{ zookeeper.config.peers }}"
        cidr_ip: "{{ internal_subnet }}"
      - proto: tcp
        from_port: "{{ zookeeper.config.leaders }}"
        to_port: "{{ zookeeper.config.leaders }}"
        cidr_ip: "{{ internal_subnet }}"    
    rules_egress:
      # Allow all outbound
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: "'zookeeper' in groups | default([])"
  register: sg_zookeeper_internal