# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# create AWS confluent platform componentns security group rules
---
- import_tasks: create-zookeeper.yml
- import_tasks: create-kafkabroker.yml
- import_tasks: create-kafkaconnect.yml
- import_tasks: create-kafkaregistry.yml
- import_tasks: create-kafkarestproxy.yml
- import_tasks: create-confluentksql.yml
- import_tasks: create-confluentcontrolcenter.yml
- import_tasks: create-cruisecontrol.yml
  
- name: CONFLUENT OVERLAY | creating confluent kafka connect replicator private external security group
  local_action:
    module: ec2_group
    name: "dnsg_{{ project }}_kafka_replicator_private_external"
    description: "kafka connect replicator external ingress and unrestricted egress rules (ansible)"
    vpc_id: "{{ specified_vpc.vpcs.0.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 0
        to_port: 65535
        cidr_ip: "{{ external_subnet }}"
    rules_egress:
      # Allow all outbound
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: "'kafka_replicator' in groups | default([])"
  register: sg_kafka_replicator_external
