# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# create AWS confluent control center security group rules
---
- name: CONFLUENT OVERLAY | creating confluent control center private external security group
  local_action:
    module: ec2_group
    name: "dnsg_{{ project }}_controlcenter_private_external"
    description: "confluent control center external ingress and unrestricted egress rules (ansible)"
    vpc_id: "{{ specified_vpc.vpcs.0.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: "{{ control.center.config.ui }}"
        to_port: "{{ control.center.config.ui }}"
        cidr_ip: "{{ external_subnet }}"
    rules_egress:
      # Allow all outbound
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: "'controlcenter' in groups | default([])"
  register: sg_controlcenter_external
