# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# install java
---
# this is unnecessary on RHEL 6
- name: KAFKA OVERLAY | installing epel package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "epel-release-{{ confluent.packages.epel_version | default(apache.packages.epel_version) }}"
  become: yes
  when:
    - got_root | default('yes')
    - ansible_distribution == 'CentOS'

- name: KAFKA OVERLAY | using first java binary in path
  raw: 'which java'
  register: java_bin
  ignore_errors: yes

- block:

  - name: KAFKA OVERLAY | checking for java-{{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }}.tar.gz
    stat: path="/tmp/java-{{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }}.tar.gz"
    register: existing_package

  - name: KAFKA OVERLAY | copying {{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }} from local {{ tenant }} area (this may take some time)
    copy:
      src: "{{ tenant_config_path }}/packages/{{ item }}"
      dest: "/tmp/{{ item }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644
    with_items:
      - "java-{{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }}.tar.gz"
    when:
      - not existing_package.stat.exists

  when:
    - java_bin.failed

- name: KAFKA OVERLAY | installing java {{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }} packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "java-{{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }}-openjdk"
    - "java-{{ confluent_kafka | ternary(confluent.packages.java_version, apache.packages.java_version) }}-openjdk-devel"
  become: yes
  when: got_root | default('yes')
