# (c) 2016 DataNexus Inc.  All Rights Reserved.
#
# OS tasks to set shell limits - these take effect at each shell login
---
- block:
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring maximum filesize (soft)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* soft fsize'
      line: "* soft fsize {{ limits.soft.fsize | default(linux.limits.soft.config.fsize) }}"
    when: not((limits.soft.config.fsize is undefined) or (limits.soft.config.fsize is none) or (limits.soft.config.fsize | trim == '')) or not((linux.limits.soft.config.fsize is undefined) or (linux.limits.soft.config.fsize is none) or (linux.limits.soft.config.fsize | trim == ''))
      
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring maximum filesize (hard)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* hard fsize'
      line: "* hard fsize {{ limits.hard.fsize | default(linux.limits.hard.config.fsize) }}"
    when: not((limits.hard.config.fsize is undefined) or (limits.hard.config.fsize is none) or (limits.hard.config.fsize | trim == '')) or not((linux.limits.hard.config.fsize is undefined) or (linux.limits.hard.config.fsize is none) or (linux.limits.hard.config.fsize | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring max number of open files (soft)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* soft nofile'
      line: "* soft nofile {{ limits.soft.nofile | default(linux.limits.soft.config.nofile) }}"
    when: not((limits.soft.config.nofile is undefined) or (limits.soft.config.nofile is none) or (limits.soft.config.nofile | trim == '')) or not((linux.limits.soft.config.nofile is undefined) or (linux.limits.soft.config.nofile is none) or (linux.limits.soft.config.nofile | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring max number of open files (hard)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* hard nofile'
      line: "* hard nofile {{ limits.hard.nofile | default(linux.limits.hard.config.nofile) }}"
    when: not((limits.hard.config.nofile is undefined) or (limits.hard.config.nofile is none) or (limits.hard.config.nofile | trim == '')) or not((linux.limits.hard.config.nofile is undefined) or (linux.limits.hard.config.nofile is none) or (linux.limits.hard.config.nofile | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring max number of processes (soft)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* soft nproc'
      line: "* soft nproc {{ limits.soft.nproc | default(linux.limits.soft.config.nproc) }}"
    when: not((limits.soft.config.nproc is undefined) or (limits.soft.config.nproc is none) or (limits.soft.config.nproc | trim == '')) or not((linux.limits.soft.config.nproc is undefined) or (linux.limits.soft.config.nproc is none) or (linux.limits.soft.config.nproc | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring max number of processes (hard)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* hard nproc'
      line: "* hard nproc {{ limits.hard.nproc | default(linux.limits.hard.config.nproc) }}"
    when: not((limits.hard.config.nproc is undefined) or (limits.hard.config.nproc is none) or (limits.hard.config.nproc | trim == '')) or not((linux.limits.hard.config.nproc is undefined) or (linux.limits.hard.config.nproc is none) or (linux.limits.hard.config.nproc | trim == ''))

  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring the core file size limit (soft)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* soft core'
      line: "* soft core {{ limits.soft.core | default(linux.limits.soft.config.core) }}"
    when: not((limits.soft.config.core is undefined) or (limits.soft.config.core is none) or (limits.soft.config.core | trim == '')) or not((linux.limits.soft.config.core is undefined) or (linux.limits.soft.config.core is none) or (linux.limits.soft.config.core | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring the core file size limit (hard)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* hard core'
      line: "* hard core {{ limits.hard.core | default(linux.limits.hard.config.core) }}"
    when: not((limits.hard.config.core is undefined) or (limits.hard.config.core is none) or (limits.hard.config.core | trim == '')) or not((linux.limits.hard.config.core is undefined) or (linux.limits.hard.config.core is none) or (linux.limits.hard.config.core | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring the max stack size (soft)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* soft stack'
      line: "* soft stack {{ limits.soft.stack | default(linux.limits.soft.config.stack) }}"
    when: not((limits.soft.config.stack is undefined) or (limits.soft.config.stack is none) or (limits.soft.config.stack | trim == '')) or not((linux.limits.soft.config.stack is undefined) or (linux.limits.soft.config.stack is none) or (linux.limits.soft.config.stack | trim == ''))
  
  - name: CONFLUENT OVERLAY (PREFLIGHT LIMITS) | configuring the max stack size (hard)
    lineinfile:
      path: "{{ linux.limits.config_file }}"
      regexp: '^\* hard stack'
      line: "* hard stack {{ limits.hard.stack | default(linux.limits.hard.config.stack) }}"
    when: not((limits.hard.config.stack is undefined) or (limits.hard.config.stack is none) or (limits.hard.config.stack | trim == '')) or not((linux.limits.hard.config.stack is undefined) or (linux.limits.hard.config.stack is none) or (linux.limits.hard.config.stack | trim == ''))

  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
