# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# OS tasks that occur post-boot and pre-appplication installation
---
# shell limits
- import_tasks: limits.yml
# kernel tuning
- import_tasks: kernel.yml
# vm tuning
- import_tasks: vm.yml

- import_tasks: upgrade-python.yml
  when:
    - not use_existing_python
