# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
#
--- 
- import_tasks: interface-facts.yml

- block:
  
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.config.logs }} exists
    file:
      path: "{{ ksql.config.logs }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.config.streams }} exists
    file:
      path: "{{ ksql.config.streams }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.config.cli_logs }} exists
    file:
      path: "{{ ksql.config.cli_logs }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: directory
      mode: 0755
      
  - name: CONFLUENT OVERLAY (KSQL) | configuring bootstrap servers for {{ ksql.service_name }}
    lineinfile:
      path: "{{ ksql.config_file }}"
      regexp: '^bootstrap.servers='
      line: "bootstrap.servers={{ groups['kafka_public'] | join(':' + kafka.config.broker_port + ',') }}:{{ kafka.config.broker_port }}"
    notify: restart ksql
    
  - name: CONFLUENT OVERLAY (KSQL) | configuring kafka broker hosts for {{ ksql.service_name }}
    lineinfile:
      path: "{{ ksql.config_file }}"
      regexp: '^listeners='
      line: "listeners=http://{{ ksql_interface_ipv4 }}:{{ ksql.config.listener_port }}"
    notify: restart ksql
  
  - name: CONFLUENT OVERLAY (KAFKA) | setting {{ ksql.service_name }} metrics reporting to {{ ksql.config.confluent_metrics }}
    lineinfile:
      path: "{{ ksql.config_file }}"
      regexp: '^confluent.support.metrics.enable='
      line: "confluent.support.metrics.enable={{ ksql.config.confluent_metrics }}"
    notify: restart ksql
    
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.user_service }} exists
    file:
      path: "{{ ksql.user_service }}"
      owner: root
      group: root
      state: directory
      mode: 0755
      
  - name: CONFLUENT OVERLAY (KSQL) | installing {{ ksql.service_name }} into {{ ksql.user_service }}
    template:
      src: confluent.ksql.j2
      dest: "{{ ksql.user_service }}/confluent-ksql"
      mode: 0755
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      
  become: yes
  
- block:
  
  - name: CONFLUENT OVERLAY (KSQL) | creating systemd override directory
    file:
      path: "{{ ksql.systemd_override }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0750
 
  - name: CONFLUENT OVERLAY (KSQL) | installing {{ ksql.service_name }} environment overrride
    template:
      src: environment.j2
      dest: "{{ ksql.systemd_override }}/override.conf"
      mode: 0640
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
    notify:
      - reload systemd
      - restart ksql
      
  - name: CONFLUENT OVERLAY (KSQL) | starting {{ ksql.service_name }}
    systemd:
      name: "{{ ksql.service_name }}"
      state: started
        
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  