# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
#
---
# this isn't strictly necessary for ksql, but the kafka broker default variables need JVM settings
- import_tasks: tune.yml
- import_tasks: interface-facts.yml

- set_fact: 
    ksql_path: "{{ (got_root | default('yes')) | ternary('/usr/bin', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/bin')) }}"

- block:
  
  # cap number of brokers in config at 5
  - name: CONFLUENT OVERLAY (KSQL) | configuring bootstrap servers for {{ ksql.service_name }}
    lineinfile:
      path: "{{ ksql.config_file }}"
      regexp: '^bootstrap.servers='
      line: "bootstrap.servers={{ groups['kafka_public'][:5] | join(':' + kafka.config.broker_port + ',') }}:{{ kafka.config.broker_port }}"
    notify: restart ksql
    
  - name: CONFLUENT OVERLAY (KSQL) | configuring kafka broker hosts for {{ ksql.service_name }}
    lineinfile:
      path: "{{ ksql.config_file }}"
      regexp: '^listeners='
      line: "listeners=http://{{ ksql_interface_ipv4 }}:{{ ksql.config.listener_port }}"
    notify: restart ksql
  
  - name: CONFLUENT OVERLAY (KAFKA) | setting {{ ksql.service_name }} metrics reporting to {{ ksql.config.confluent_metrics }}
    lineinfile:
      path: "{{ ksql.config_file }}"
      regexp: '^confluent.support.metrics.enable='
      line: "confluent.support.metrics.enable={{ ksql.config.confluent_metrics }}"
    notify: restart ksql
    
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.user_service }} exists
    file:
      path: "{{ ksql.user_service }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0755
      
  - name: CONFLUENT OVERLAY (KSQL) | installing {{ ksql.service_name }} into {{ ksql.user_service }}
    template:
      src: confluent.ksql.j2
      dest: "{{ ksql.user_service }}/confluent-ksql"
      mode: 0755
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
  
  # this is a little odd because we either need to be root or the zookeeper_user
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ (got_root | default('yes')) | ternary('/var/run', (confluent_root + '/var/run')) }} exists
    file:
      path: "{{ (got_root | default('yes')) | ternary('/var/run', (confluent_root + '/var/run')) }}"
      owner: "{{ (got_root | default('yes')) | ternary('root', ksql.user) }}"
      group: "{{ (got_root | default('yes')) | ternary('root', ksql.group) }}"
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.config.logs }} exists
    file:
      path: "{{ ksql.config.logs }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.config.streams }} exists
    file:
      path: "{{ ksql.config.streams }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0755
  
  - name: CONFLUENT OVERLAY (KSQL) | ensuring {{ ksql.config.cli_logs }} exists
    file:
      path: "{{ ksql.config.cli_logs }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0755
      
  # the thinking here is that these files are either restricted or not and that drives our escalation  
  become: "{{ got_root | default('yes') }}"
    
- block:
  
  - name: CONFLUENT OVERLAY (KSQL) | creating systemd override directory
    file:
      path: "{{ ksql.systemd_override }}"
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
      state: directory
      mode: 0750
    when: 
      - ansible_distribution_version is version_compare('7', '>=')
      
  - name: CONFLUENT OVERLAY (KSQL) | installing {{ ksql.service_name }} environment overrride
    template:
      src: environment.j2
      dest: "{{ ksql.systemd_override }}/override.conf"
      mode: 0640
      owner: "{{ ksql.user }}"
      group: "{{ ksql.group }}"
    notify:
      - reload systemd
      - restart ksql
    when: 
      - ansible_distribution_version is version_compare('7', '>=')
      
  - name: CONFLUENT OVERLAY (KSQL) | enabling {{ ksql.service_name }} by systemd
    systemd:
      name: "{{ ksql.service_name }}"
      enabled: yes
    when: 
      - ansible_distribution_version is version_compare('7', '>=')
  
  - name: CONFLUENT OVERLAY (KSQL) | installing sysvinit {{ ksql.service_name }} script
    template:
      src: confluent.sysvinit.j2
      dest: "/etc/init.d/{{ ksql.service_name }}"
      mode: 0755
      owner: root
      group: root
    when: 
      - ansible_distribution_version is version_compare('7', '<')
      
  - name: CONFLUENT OVERLAY (KSQL) | enabling {{ ksql.service_name }} by sysvinit
    sysvinit:
      name: "{{ ksql.service_name }}"
      enabled: yes
    when: 
      - ansible_distribution_version is version_compare('7', '<')
      
  become: yes
  when:
    - got_root | default('yes') 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  