# configuration variables for kafka broker services
kafka:
  linux:
    limits:
      config_file: /etc/security/limits.conf
      soft:
        config:
          nofile: 100000
      hard:
        config:
          nofile: 100000
  apache:
    user: kafka
    group: kafka
    config_file: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/config/server.properties"
    service_name: apache-kafka
    systemd_override: /etc/systemd/system/apache-kafka.service.d
  confluent:
    user: "{{ (got_root | default('yes')) | ternary('cp-kafka', ansible_user) }}"
    group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    config_file: "{{ (got_root | default('yes')) | ternary('/etc/kafka/server.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/kafka/server.properties')) }}"
    systemd_override: /etc/systemd/system/confluent-kafka.service.d
    service_name: confluent-kafka 
  user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
  environment:
    KAFKA_HEAP_OPTS: "-Xmx{{ jvm_heap_mem }}g -Xms{{ jvm_heap_mem }}g"
    KAFKA_JVM_PERFORMANCE_OPTS: "-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
    LOG_DIR: "{{ (got_root | default('yes')) | ternary('/var/log/kafka', confluent_root + '/var/log/kafka')}}"
    # this does not seem to work to eliminate the subject alternative name error
    # KAFKA_OPTS: "-Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true"
    # uncomment the following line to turn on JMX on port 10101
    # JMX_PORT: 10101
  config:
    # kafka defaults to topic deletion 'true', but we apply any tenant settings if defined
    topic_deletion: "{{ (tenant_topic_deletion is defined | default('yes')) | ternary(tenant_topic_deletion, none) }}"
    confluent_metrics: False
    # this needs to be quoted as a string for concatenation purposes
    # if this gets changed it needs to be changed under connect defaults
    broker_port: '9092'
    num_network_threads: 8
    num_io_threads: 16 
    socket_send_buffer_bytes: 102400
    socket_receive_buffer_bytes: 102400
    socket_request_max_bytes: 104857600
    # this needs to be quoted as a string for concatenation purposes
    logDir: "{{ broker_data_dir | default('/var/lib/kafka/data') }}"
    default_num_partitions: 1
    num_recovery_threads_per_data_dir: 2
    offsets_topic_replication_factor: "{{ ((groups['kafka_broker'] | length) > 3) | ternary(3, groups['kafka_broker'] | length) }}"
    # default 1
    transaction_state_log_replication_factor:
    transaction_state_log_min_isr: "{{ ((groups['kafka_broker'] | length) > 2) | ternary(2, groups['kafka_broker'] | length) }}"
    log_retention_hours: "{{ tenant_log_retention_hours | default(168) }}"
    # this logic is a little more complicated because log.retention.bytes is not enabled by default
    log_retention_bytes: "{{ (tenant_log_retention_bytes is defined | default('yes')) | ternary(tenant_log_retention_bytes, none) }}"
    log_retention_ms: "{{ (tenant_log_retention_ms is defined | default('yes')) | ternary(tenant_log_retention_ms, none) }}"
    log_segment_bytes: "{{ tenant_log_segment_bytes | default(1073741824) }}"
    log_retention_check_interval_ms: "{{ tenant_log_retention_check_interval_ms | default(300000) }}"
    log_cleaner_delete_retention_ms: "{{ (tenant_log_cleaner_delete_retention_ms is defined | default('yes')) | ternary(tenant_log_cleaner_delete_retention_ms, none) }}"
    zookeeper_connection_timeout_ms: "{{ tenant_zookeeper_timeout_ms | default(6000) }}"
    metric_reporters: io.confluent.metrics.reporter.ConfluentMetricsReporter
    confluent_metrics_reporter_topic_replicas: "{{ ((groups['kafka_broker'] | length) > 3) | ternary(3, groups['kafka_broker'] | length) }}"
    # default 0
    group_initial_rebalance_delay_ms:
    # default 10
    background_threads:
    # default 2
    num_replica_alter_log_dirs_threads:
    # default 1
    num_replica_fetchers:
    # default 500 
    queued_max_requests:
    # default 5000
    replica_high_watermark_checkpoint_interval_ms:
    # default 10000
    replica_lag_time_max_ms:   
    # default 65536
    replica_socket_receive_buffer_bytes:
    # default 30000
    replica_socket_timeout_ms:
    # default 30000
    request_timeout_ms:
    # default 900000
    transaction_max_timeout_ms:
    # default False
    unclean_leader_election_enable:
    # default 30000
    controller_socket_timeout_ms:
    # default 134217728
    log_cleaner_dedupe_buffer_size:
    # default 524288
    log_cleaner_io_buffer_size:
    log_cleaner_threads:
    ssl_endpoint_identification_algorithm: ""
    confluent_metrics_reporter_ssl_endpoint_identification_algorithm: ""
