# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during confluent connect installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: yes
  
- name: restart connect
  systemd:
    name: "{{ connect_service_name }}"
    state: restarted
  become: yes
