# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart zookeeper
  listen: "restart zookeeper"
  systemd:
    name: "{{ zookeeper_service_name }}"
    state: restarted
  become: true

- name: pause
  listen: "restart zookeeper"
  pause:
    seconds: 30
