# (c) 2018 DataNexus Inc.  All Rights Reserved.
---
apache:
  packages:
    epel_version: '7-11'
    java_version: '1.8.0'
    kafka_version: '2.1.1'
    scala_version: '2.12'
  install_dir: /usr/local
  user: kafka
  group: kafka
  config_file: server.properties
