# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
---
confluent:
  packages:
    connect_elasticsearch: '5.3.1'
    java_version: '1.8.0'
    confluent_version: '5.3'
    minor_release: '0'
apache:
  packages:
    epel_version: '7-11'
    java_version: '1.8.0'
    kafka_version: '2.3.1'
    scala_version: '2.12'
  install_dir: /usr/local
  user: kafka
  group: kafka
  config_file: server.properties
