# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# install java
---
# this is unnecessary on RHEL 6
- name: CONFLUENT OVERLAY | installing epel package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "epel-release-{{ packages.epel_version }}"
  when: ansible_distribution == 'CentOS'
  become: yes
  
- name: CONFLUENT OVERLAY | installing java {{ packages.java_version }} packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "java-{{ packages.java_version }}-openjdk"
    - "java-{{ packages.java_version }}-openjdk-devel"
  become: yes