# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
#
---
- set_fact:
    confluent_platform_version: "{{ confluent_distribution }}-{{ application_version | default(packages.scala_version) }}"
        
- name: CONFLUENT OVERLAY | installing confluent platform public key
  rpm_key:
    state: present
    key: "{{ confluent_public_key }}"
  become: yes

# CentOS / Redhat 7
- block:
  
  - import_tasks: install-java.yml
      
  - name: CONFLUENT OVERLAY | configuring confluent platform repo for CentOS / Redhat
    template:
      src: confluent-repo.j2
      dest: /etc/yum.repos.d/confluent.repo
      mode: 0644

  - name: CONFLUENT OVERLAY | installing {{ application_version | default(confluent_platform_version) }}
    package:
      name: "{{ application_version | default(confluent_platform_version) }}"
      state: present
    notify: yum-clean-all
        
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
