# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during confluent platform installation
---
- name: restart controlcenter
  systemd:
    name: "{{ control.center.service_name }}"
    state: restarted
  become: true
  
- name: reload systemd
  command: systemctl daemon-reload
  become: true