# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: true

- name: restart kafkarest
  systemd:
    name: "{{ kafkarest.service_name }}"
    state: restarted
  become: true
