# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# handlers used during confluent platform installation
---
- name: reload systemd
  command: systemctl daemon-reload
  become: yes
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')
    
- name: systemd kafkarest
  listen: "restart kafkarest"
  systemd:
    name: "{{ kafkarest.service_name }}"
    state: restarted
  become: yes
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '>=')

- name: sysvinit kafkarest
  listen: "restart kafkarest"
  sysvinit:
    name: "{{ kafkarest.service_name }}"
    state: restarted
  become: yes
  when: 
    - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    - ansible_distribution_version is version_compare('7', '<')
