connect:
  distributed:
    config_file: /etc/kafka/connect-distributed.properties
    service_name: confluent-kafka-connect
    systemd_configuration: /usr/lib/systemd/system/confluent-kafka-connect.service
    group: confluent
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx2G"
    config:
      consumer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      producer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      ssl.endpoint.identification.algorithm: ""
      consumer.ssl.endpoint.identification.algorithm: ""
      producer.ssl.endpoint.identification.algorithm: ""
      config_storage_replication_factor: 3
      config_storage_topic: connect-configs
      group_id: connect-cluster
      internal_key_converter: org.apache.kafka.connect.json.JsonConverter
      internal_key_converter_schemas_enable: true
      internal_value_converter: org.apache.kafka.connect.json.JsonConverter
      internal_value_converter_schemas_enable: true
      offset_flush_interval_ms: 10000
      offset_storage_replication_factor: 3
      offset_storage_topic: connect-offsets
      status_storage_replication_factor: 3
      status_storage_topic: connect-status
      key_converter: io.confluent.connect.avro.AvroConverter
      key_converter_enable: false
      value_converter: io.confluent.connect.avro.AvroConverter
      value_converter_enable: false
kafka:
   config:
     # if this gets changed it needs to be changed under kafka defaults
     broker_port: '9092'
kafkarest:
  config:
    rest_port: 8083
