# configuration variables for kafka distributed connector services
connect:
  distributed:
    config_file: /etc/kafka/connect-distributed.properties
    service_name: confluent-kafka-connect
    systemd_override: /etc/systemd/system/confluent-kafka-connect.service.d
    user_service: /usr/local/bin
    user: cp-kafka-connect
    group: confluent
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx{{ jvm_heap_mem }}g"
    config:
      rest_port: 8083
      consumer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      producer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      ssl.endpoint.identification.algorithm: ""
      consumer.ssl.endpoint.identification.algorithm: ""
      producer.ssl.endpoint.identification.algorithm: ""
      config_storage_replication_factor: 3
      config_storage_topic: connect-configs
      group_id: connect-cluster
      key_converter: org.apache.kafka.connect.json.JsonConverter
      key_converter_schemas_enable: false
      value_converter: org.apache.kafka.connect.json.JsonConverter
      value_converter_schemas_enable: false
      offset_flush_interval_ms: 10000
      offset_storage_replication_factor: 3
      offset_storage_topic: connect-offsets
      status_storage_replication_factor: 3
      status_storage_topic: connect-status
broker:
   config:
     # if this gets changed it needs to be changed under kafka defaults
     broker_port: '9092'
