# configuration variables for kafka distributed connector services
connect:
  distributed:
    apache:
      config_file: "{{ apache.install_dir }}/kafka_{{ apache.packages.scala_version }}-{{ apache.packages.kafka_version }}/config/connect-distributed.properties"
      service_name: apache-kafka-connect
      systemd_override: /etc/systemd/system/apache-kafka-connect.service.d
      user: kafka
      group: kafka
    confluent:
      config_file: "{{ (got_root | default('yes')) | ternary('/etc/kafka/connect-distributed.properties', (confluent_root + '/confluent-' + confluent.packages.confluent_version + '.' + confluent.packages.minor_release.split('-')[0] + '/etc/kafka/connect-distributed.properties')) }}"
      service_name: confluent-kafka-connect
      systemd_override: /etc/systemd/system/confluent-kafka-connect.service.d
      user: "{{ (got_root | default('yes')) | ternary('cp-kafka-connect', ansible_user) }}"
      group: "{{ (got_root | default('yes')) | ternary('confluent', ansible_user) }}"
    user_service: "{{ (got_root | default('yes')) | ternary('/usr/local/bin', confluent_root + '/bin')}}"
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx{{ jvm_heap_mem }}g"
      LOG_DIR: "{{ (got_root | default('yes')) | ternary('/var/log/kafka', confluent_root + '/var/log/kafka')}}"
    config:
      rest_port: '8083'
      consumer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      producer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      ssl.endpoint.identification.algorithm: ""
      consumer.ssl.endpoint.identification.algorithm: ""
      producer.ssl.endpoint.identification.algorithm: ""
      config_storage_replication_factor: "{{ ((groups['kafka_broker'] | length) > 3) | ternary(3, groups['kafka_broker'] | length) }}"
      config_storage_topic: connect-configs
      group_id: connect-cluster
      key_converter: org.apache.kafka.connect.json.JsonConverter
      key_converter_schemas_enable: false
      value_converter: org.apache.kafka.connect.json.JsonConverter
      value_converter_schemas_enable: false
      offset_flush_interval_ms: 10000
      offset_storage_replication_factor: "{{ ((groups['kafka_broker'] | length) > 3) | ternary(3, groups['kafka_broker'] | length) }}"
      offset_storage_topic: connect-offsets
      status_storage_replication_factor: "{{ ((groups['kafka_broker'] | length) > 3) | ternary(3, groups['kafka_broker'] | length) }}"
      status_storage_topic: connect-status
