# configuration variables for kafka distributed connector services
connect:
  distributed:
    apache:
      config_file: "{{ apache.install_dir }}/kafka_{{ packages.scala_version }}-{{ packages.kafka_version }}/config/connect-distributed.properties"
      service_name: apache-kafka-connect
      systemd_override: /etc/systemd/system/apache-kafka-connect.service.d
      user: kafka
      group: kafka
    confluent:
      config_file: /etc/kafka/connect-distributed.properties
      service_name: confluent-kafka-connect
      systemd_override: /etc/systemd/system/confluent-kafka-connect.service.d
      user: cp-kafka-connect
      group: confluent
    user_service: /usr/local/bin
    environment:
      KAFKA_HEAP_OPTS: "-Xms256M -Xmx{{ jvm_heap_mem }}g"
      LOG_DIR: /var/log/kafka
    config:
      rest_port: '8083'
      consumer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
      producer.interceptor.classes: io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      ssl.endpoint.identification.algorithm: ""
      consumer.ssl.endpoint.identification.algorithm: ""
      producer.ssl.endpoint.identification.algorithm: ""
      config_storage_replication_factor: 3
      config_storage_topic: connect-configs
      group_id: connect-cluster
      key_converter: org.apache.kafka.connect.json.JsonConverter
      key_converter_schemas_enable: false
      value_converter: org.apache.kafka.connect.json.JsonConverter
      value_converter_schemas_enable: false
      offset_flush_interval_ms: 10000
      offset_storage_replication_factor: 3
      offset_storage_topic: connect-offsets
      status_storage_replication_factor: 3
      status_storage_topic: connect-status
