# (c) 2016 DataNexus Inc.  All Rights Reserved.
# Licensed software not for distribution
#
# automatically set facts based on interfaces present
---   
- name: setting eth0 to all interfaces
  set_fact:
    connector_rest_interface: "{{ hostvars[inventory_hostname].ansible_eth0.device }}"
    connector_rest_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}"
    connector_rest_broadcast_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.broadcast }}"
    connector_rest_metrics_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth0.ipv4.address }}"
  when: hostvars[inventory_hostname].ansible_eth0 is defined

- name: setting eth1 to kafka connector and metrics
  set_fact:
    connector_rest_interface: "{{ hostvars[inventory_hostname].ansible_eth1.device }}"
    connector_rest_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
    connector_rest_broadcast_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.broadcast }}"
    connector_rest_metrics_interface_ipv4: "{{ hostvars[inventory_hostname].ansible_eth1.ipv4.address }}"
  when: hostvars[inventory_hostname].ansible_eth1 is defined
