# (c) Copyright 2018 DataNexus Inc.  All Rights Reserved.
#
#
---
# either set what the user specifies or default to 2g max heap
- name: CONFLUENT OVERLAY (CONNECT TUNING) | jvm max heap size is...{{ ((jvm_heap | default('auto')) | int != 0) | ternary ((jvm_heap),('2g')) }}
  set_fact: jvm_heap_mem="{{ ((jvm_heap | default('auto')) | int != 0) | ternary ((jvm_heap),('2')) }}"    

- name: CONFLUENT OVERLAY (CONNECT TUNING) | verifying 2gb needed is available for connector process
  assert:
    that:
      - ansible_memfree_mb >= 2048
    fail_msg: "heap space inadequate: allocate more RAM, decrease requested heap space, or set 'jvm_heap' to 'auto'"
    success_msg: "system has enough heap space"
